### ISSUE TITLE
Does this module run on Mac? 

### ISSUE THREAD

**Issue by jr-leary7** [sdomanskyi/DigitalCellSorter#3]
When running `DCS.process(my_df)`, I get this error: `AttributeError: module "time" has no attribute "thread_time"`. From [this link](https://docs.python.org/3/library/time.html) I see that `thread_time()` is available with Python >= 3.7, on systems Windows/Linux/Unix systems that support `CLOCK_THREAD_CPUTIME_ID`. However, I can't find anything regarding whether or not the Unix system that MacOS is built on supports that specific C++ function. Have you personally run `DCS.process()` on a Mac machine / do you know of users that have successfully done so? If not, I'll assume that for now I won't be able to use this module.

**Comment by sdomanskyi** [comment]
The latest version of DigitalCellSorter has been extensively used with Windows and Linux operating systems. On MacOS the latest version of the package had been tested for installation only.

I have added the following note in the main readme.md:
> Note: We are currently preparing a manuscript describing the toolkit located this repository. If you want to access the package detailed in our latest publication of Polled Digital Cell Sorter go to https://zenodo.org/record/2603265 and download the package (v1.1).

**Comment by jr-leary7** [comment]
Through StackOverflow it's been determined that the `CLOCK_THREAD_CPUTIME` C++ function isn't available on Mac systems, thus `DCS.process()` will not run.
